function [opt] = mvpa_chooseMask(opt)

    opt.maskName = [];
    
    switch opt.mask
        
        case 'jubrain'
            
            for iSub = 1:numel(opt.subjects)
                
                subID = opt.subjects{iSub};
                
                opt.maskName = horzcat(opt.maskName, ...
                        { ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-L_space-MNI_label-AG_vox-300.nii'), ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-R_space-MNI_label-AG_vox-300.nii') ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-L_space-MNI_label-PSPL_vox-300.nii'), ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-R_space-MNI_label-PSPL_vox-300.nii') ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-L_space-MNI_label-hIPS_vox-300.nii'), ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-R_space-MNI_label-hIPS_vox-300.nii') ...                       
                          });
                      
                 opt.maskLabel = {'lAG_ju_300vx', 'rAG_ju_300vx',...
                                  'lPSPL_ju_300vx', 'rPSPL_ju_300vx',...
                                  'lhIPS_ju_300vx', 'rhIPS_ju_300vx'};
            end
            
        case 'neurosynth'
            
            for iSub = 1:numel(opt.subjects)
                
                subID = opt.subjects{iSub};
                
                opt.maskName = horzcat(opt.maskName, ...
                        { ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-L_space-MNI_label-IPS_vox-300.nii'), ...
                          strcat('sub-', num2str(subID),...
                          '_hemi-R_space-MNI_label-IPS_vox-300.nii') ...                   
                          });
                      
                 opt.maskLabel = {'lIPS_neurosynth_300vx',...
                                  'rIPS_neurosynth_300vx'};
                              
            end
            
        case 'activationMap'
            
            for iSub = 1:numel(opt.subjects)
                
                subID = opt.subjects{iSub};
                
                opt.maskName = horzcat(opt.maskName, ...
                        { ...
                          strcat('sub-', num2str(subID),...
                          '_smth6_activation_parietal.nii'), ...                   
                          });
                      
                      
                 opt.maskLabel = {'activationMap_1000vx',...
                                  };
                              
            end
            
           
            
    end
                              
end